[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sefaria-mcp"
version = "0.1.0"
description = "A FastMCP server for Sefaria"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dependencies = [
    "fastmcp[apps]==3.4.2",
    "mcp==1.27.2",
    "pydantic==2.13.4",
    "pydantic-core==2.46.4",
    "hdate",
    "requests",
    "tzdata",
    "pillow",
    "fastapi",
    "uvicorn",
    "python-dotenv",
    "prometheus-fastapi-instrumentator",
    "prometheus-client"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
]

[project.scripts]
sefaria-mcp = "sefaria_mcp.main:main" 
